import {
  Accessibility,
  FavoriteBorder,
  Healing,
  LocalHospital,
  MonitorHeart,
  Psychology,
  Restaurant,
  Spa,
  Visibility,
} from "@mui/icons-material";

export const specialties = [
  {
    id: 1,
    name: "Clínica Geral",
    description: "Atendimento médico geral e cuidados preventivos.",
    professionals: 18,
    monthlyAppointments: 1680,
    professionalsGrowth: 8,
    appointmentsGrowth: 12,
    icon: LocalHospital,
  },
  {
    id: 2,
    name: "Cardiologia",
    description: "Diagnóstico e tratamento do coração.",
    professionals: 12,
    monthlyAppointments: 1450,
    professionalsGrowth: 8,
    appointmentsGrowth: 12,
    icon: FavoriteBorder,
  },
  {
    id: 3,
    name: "Dermatologia",
    description: "Cuidados com a pele, cabelo e unhas.",
    professionals: 7,
    monthlyAppointments: 480,
    professionalsGrowth: 7,
    appointmentsGrowth: 6,
    icon: Spa,
  },
  {
    id: 4,
    name: "Endocrinologia",
    description: "Tratamento hormonal e metabólico.",
    professionals: 6,
    monthlyAppointments: 390,
    professionalsGrowth: 5,
    appointmentsGrowth: 9,
    icon: MonitorHeart,
  },
  {
    id: 5,
    name: "Ginecologia",
    description: "Cuidados com a saúde da mulher.",
    professionals: 10,
    monthlyAppointments: 920,
    professionalsGrowth: 6,
    appointmentsGrowth: 10,
    icon: Healing,
  },
  {
    id: 6,
    name: "Neurologia",
    description: "Cuidados para doenças do sistema nervoso.",
    professionals: 8,
    monthlyAppointments: 890,
    professionalsGrowth: 5,
    appointmentsGrowth: 10,
    icon: Psychology,
  },
  {
    id: 7,
    name: "Nutrição",
    description: "Orientação alimentar e nutricional.",
    professionals: 9,
    monthlyAppointments: 760,
    professionalsGrowth: 4,
    appointmentsGrowth: 8,
    icon: Restaurant,
  },
  {
    id: 8,
    name: "Ortopedia",
    description: "Tratamento de ossos e articulações.",
    professionals: 10,
    monthlyAppointments: 1120,
    professionalsGrowth: 4,
    appointmentsGrowth: 9,
    icon: Accessibility,
  },
  {
    id: 9,
    name: "Pediatria",
    description: "Cuidados médicos para crianças.",
    professionals: 15,
    monthlyAppointments: 2100,
    professionalsGrowth: 6,
    appointmentsGrowth: 18,
    icon: LocalHospital,
  },
  {
    id: 10,
    name: "Psicologia",
    description: "Acompanhamento da saúde mental.",
    professionals: 11,
    monthlyAppointments: 980,
    professionalsGrowth: 9,
    appointmentsGrowth: 14,
    icon: Visibility,
  },
];
